services:
  webdash:
    container_name: webdash
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data:${DATA_PATH:-/app/data}
    env_file:
      - .env
    restart: unless-stopped
