# Default - Webdash Version
server {

    listen 80 default_server;
    listen 443 default_server;

    server_name *.webdash.local;

    root /config/www/default;
}

# Home - Webdash Version
server {

    listen 80;
    listen 443;

    server_name home.webdash.local;

    root /config/www/home;
}

# Work - Webdash Version
server {

    listen 80;
    listen 443;

    server_name work.webdash.local;

    root /config/www/work;
}